(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("map7",
{ "compressionlevel":-1,
 "height":9,
 "infinite":false,
 "layers":[
        {
         "id":2,
         "image":"..\/Resources\/backgroundLevel7.png",
         "name":"Background",
         "opacity":1,
         "type":"imagelayer",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Objects",
         "objects":[
                {
                 "id":1,
                 "template":"..\/Templates\/crate.tx",
                 "x":928,
                 "y":384
                }, 
                {
                 "id":2,
                 "template":"..\/Templates\/crate.tx",
                 "x":928,
                 "y":352
                }, 
                {
                 "id":3,
                 "template":"..\/Templates\/crate.tx",
                 "x":864,
                 "y":448
                }, 
                {
                 "id":9,
                 "template":"..\/Templates\/crate.tx",
                 "x":672,
                 "y":512
                }, 
                {
                 "id":10,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":304,
                 "y":224
                }, 
                {
                 "id":11,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":304,
                 "y":224
                }, 
                {
                 "id":12,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":304,
                 "y":256
                }, 
                {
                 "id":13,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":304,
                 "y":288
                }, 
                {
                 "id":14,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":304,
                 "y":320
                }, 
                {
                 "id":15,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":304,
                 "y":352
                }, 
                {
                 "id":16,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":304,
                 "y":384
                }, 
                {
                 "id":17,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":128,
                 "y":512
                }, 
                {
                 "id":18,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":560,
                 "y":480
                }, 
                {
                 "id":19,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":928,
                 "y":320
                }, 
                {
                 "id":20,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":848,
                 "y":256
                }, 
                {
                 "id":21,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":752,
                 "y":240
                },
            
                {
                 "id":22,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":832,
                 "y":448
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":4,
 "nextobjectid":23,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.11.0",
 "tileheight":64,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/Tilesets\/coin_small_gold.tsx"
        }],
 "tilewidth":64,
 "type":"map",
 "version":"1.10",
 "width":16
});