(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("map8",
{ "compressionlevel":-1,
 "height":9,
 "infinite":false,
 "layers":[
        {
         "id":2,
         "image":"..\/Resources\/backgroundLevel8.png",
         "name":"Background",
         "opacity":1,
         "type":"imagelayer",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Objects",
         "objects":[
                {
                 "id":1,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":720,
                 "y":432
                }, 
                {
                 "id":2,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":592,
                 "y":368
                }, 
                {
                 "id":3,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":464,
                 "y":368
                }, 
                {
                 "id":4,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":336,
                 "y":432
                }, 
                {
                 "id":5,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":208,
                 "y":176
                }, 
                {
                 "id":6,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":336,
                 "y":128
                }, 
                {
                 "id":7,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":464,
                 "y":176
                }, 
                {
                 "id":8,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":592,
                 "y":128
                }, 
                {
                 "id":9,
                 "template":"..\/Templates\/coin_small_gold.tx",
                 "x":720,
                 "y":176
                }, 
                {
                 "id":10,
                 "template":"..\/Templates\/crate.tx",
                 "x":80,
                 "y":320
                }, 
                {
                 "id":11,
                 "template":"..\/Templates\/crate.tx",
                 "x":64,
                 "y":288
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":4,
 "nextobjectid":12,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.11.0",
 "tileheight":64,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/Tilesets\/spikes.tsx"
        }, 
        {
         "firstgid":5,
         "source":"..\/Tilesets\/coin_small_gold.tsx"
        }, 
        {
         "firstgid":11,
         "source":"..\/Tilesets\/crate.tsx"
        }],
 "tilewidth":64,
 "type":"map",
 "version":"1.10",
 "width":16
});